#! /bin/bash

# Configuration files
PERCENTAGE_FILE="/etc/asus-health-charging.d/percentage"
INTERFACE_FILE="/etc/asus-health-charging.d/interface"

# Base function
setter () {
	if (( $1 >= 15 && $1 <= 100 ))
	then
		ASUS_HEALTH_PERCENTAGE=$1
		echo "$ASUS_HEALTH_PERCENTAGE" > "$PERCENTAGE_FILE"
		echo "$ASUS_HEALTH_PERCENTAGE" > "$ASUS_HEALTH_INTERFACE"
	else
		>&2 echo "asus-health-charging: invalid parameter."
		>&2 echo "asus-health-charging: set a percentage beetween 15 and 100."
		exit 1
	fi
}

# Interface check
if [ ! -f "$INTERFACE_FILE" ]
then
	>&2 echo "asus-health-charging: \"$INTERFACE_FILE\" file not found!"
	exit 1
fi

ASUS_HEALTH_INTERFACE=$(cat "$INTERFACE_FILE")

if [ ! -f "$ASUS_HEALTH_INTERFACE" ]
then
	>&2 echo "asus-health-charging: \"$ASUS_HEALTH_INTERFACE\" file not found!"
	exit 1
fi
# End of interface check

# Parameter check
case $1 in
"--current")
	cat "$ASUS_HEALTH_INTERFACE"
	;;
"--restore")
	if [ -f "$PERCENTAGE_FILE" ]
	then
	    echo "asus-health-charging: Restoring from configuration."
		setter $(cat "$PERCENTAGE_FILE")
	else
		>&2 echo "asus-health-charging: \"$PERCENTAGE_FILE\" file not found!"
		>&2 echo "asus-health-charging: reverting to default value 100."
		setter 100
	fi
	;;
*)
	setter $1
	;;
esac
